repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        entry: poetry
        language: system
        args: ["check"]
        pass_filenames: false

      - id: poetry-install
        name: poetry-install
        entry: poetry
        language: system
        args: ["install", "--no-root"]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff-format
        args: []
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
          - --select=ALL
          - --ignore=A002,B008,D100,D101,D102,D103,D104,D107,D205,D211,D213,FIX002,N999,S101,S311,TD001,TD002,TD003,TD004,TD005,FIX001,SLF001,ANN401,D106,ARG001,RUF012,S105,DJ008,DJ001,ARG002,TRY401
        exclude: |
          migrations/|
          settings.py