repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        entry: poetry
        language: system
        args: ["check"]
        pass_filenames: false

      - id: poetry-install
        name: poetry-install
        entry: poetry
        language: system
        args: ["install"]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff-format
        args: []
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
          - --select=ALL

